#!/usr/bin/env python3
# Generate the classic Mac icon family (ICN#/icl8/ics#/ics8) + BNDL/FREF/signature
# as Rez `data` statements, from the Casquinha otter art. So the app shows the
# otter in the Finder instead of a generic app icon.
#
#   python3 tools/gen_icons.py            # -> os9/icon.r
import sys
from PIL import Image, ImageDraw

SRC = "design/icon/casquinha-icon.png"
OUT = "os9/icon.r"
CREATOR = "Casq"          # must match add_application CREATOR
RID = 128

# --- the standard Macintosh 256-color system palette (clut 8) ---------------
def mac_palette():
    vals  = [0xFF, 0xCC, 0x99, 0x66, 0x33, 0x00]
    pal   = [(r, g, b) for r in vals for g in vals for b in vals]   # 216-color cube
    extra = [0xEE, 0xDD, 0xBB, 0xAA, 0x88, 0x77, 0x55, 0x44, 0x22, 0x11]
    for v in extra: pal.append((v, 0, 0))
    for v in extra: pal.append((0, v, 0))
    for v in extra: pal.append((0, 0, v))
    for v in extra: pal.append((v, v, v))
    return pal                                                      # 256 entries

PAL = mac_palette()

def nearest(rgb):
    r, g, b = rgb
    best, bi = 1 << 30, 0
    for i, (pr, pg, pb) in enumerate(PAL):
        d = (pr - r) ** 2 + (pg - g) ** 2 + (pb - b) ** 2
        if d < best:
            best, bi = d, i
    return bi

# --- load art + derive an in-shape mask (flood-fill the white frame away) -----
src = Image.open(SRC).convert("RGBA")
w, h = src.size
rgb = src.convert("RGB")
SENT = (255, 0, 255)
for seed in [(0, 0), (w - 1, 0), (0, h - 1), (w - 1, h - 1)]:
    ImageDraw.floodfill(rgb, seed, SENT, thresh=48)
alpha = Image.new("L", (w, h))
alpha.putdata([0 if p == SENT else 255 for p in rgb.getdata()])
src.putalpha(alpha)
bb = src.getbbox()
if bb:
    src = src.crop(bb)
s = min(src.size)
src = src.crop(((src.size[0] - s) // 2, (src.size[1] - s) // 2,
                (src.size[0] - s) // 2 + s, (src.size[1] - s) // 2 + s))

def bits_to_bytes(bits):
    out = bytearray()
    for i in range(0, len(bits), 8):
        byte = 0
        for j in range(8):
            byte = (byte << 1) | (bits[i + j] & 1)
        out.append(byte)
    return bytes(out)

def render(size):
    im = src.resize((size, size), Image.LANCZOS)
    px = im.load()
    idx = bytearray()          # 8-bit indices
    icon_bits = []             # 1 where dark & in-shape
    mask_bits = []             # 1 where in-shape
    for y in range(size):
        for x in range(size):
            r, g, b, a = px[x, y]
            inshape = a >= 128
            mask_bits.append(1 if inshape else 0)
            lum = (r * 30 + g * 59 + b * 11) // 100
            icon_bits.append(1 if (inshape and lum < 128) else 0)
            idx.append(nearest((r, g, b)) if inshape else 0)
    icn = bits_to_bytes(icon_bits) + bits_to_bytes(mask_bits)   # icon plane + mask
    return bytes(idx), icn

def hexstr(b):
    return "".join("%02X" % x for x in b)

idx32, icn_l = render(32)      # icl8 (1024) ; ICN# (256)
idx16, icn_s = render(16)      # ics8 (256)  ; ics# (64)

# BNDL: signature + resID 0 + [FREF:(0->RID)] [ICN#:(0->RID)]
def ost(s):  # OSType -> hex
    return hexstr(s.encode("mac_roman"))
bndl = (ost(CREATOR) + "0000" + "0001" +
        ost("FREF") + "0000" + "0000" + "%04X" % RID +
        ost("ICN#") + "0000" + "0000" + "%04X" % RID)
fref = ost("APPL") + "0000" + "00"                 # type, iconLocalID 0, name ""
sig  = "%02X" % len("Casquinha") + hexstr(b"Casquinha")

def data_res(typ, rid, hx):
    # split into 32-byte lines for readability
    lines = [hx[i:i+64] for i in range(0, len(hx), 64)]
    body = "\n        ".join('$"%s"' % ln for ln in lines)
    return "data '%s' (%d) {\n        %s\n};\n\n" % (typ, rid, body)

with open(OUT, "w") as f:
    f.write("/* icon.r - GENERATED by tools/gen_icons.py. The Casquinha otter icon\n"
            "   family + BNDL/FREF/signature, so the Finder shows the otter. */\n\n")
    f.write(data_res("BNDL", RID, bndl))
    f.write(data_res("FREF", RID, fref))
    f.write(data_res(CREATOR, 0, sig))
    f.write(data_res("ICN#", RID, hexstr(icn_l)))
    f.write(data_res("icl8", RID, hexstr(idx32)))
    f.write(data_res("ics#", RID, hexstr(icn_s)))
    f.write(data_res("ics8", RID, hexstr(idx16)))

print("wrote %s (creator '%s', icon id %d)" % (OUT, CREATOR, RID))
